source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'MRDetectBpmOperation_Example', :exclusive => true do
  pod "MRDetectBpmOperation", :path => "../"
  pod "ErrorKit"
end

target 'MRDetectBpmOperation_Tests', :exclusive => true do
  pod "MRDetectBpmOperation", :path => "../"
end

post_install do |installer|
    system("git submodule update --init --recursive")
end
